# =========================
# DEV PROFILE
# =========================

# Affiche les requêtes SQL générées par Hibernate
#spring.jpa.show-sql=true

# Formate les requêtes SQL dans les logs
#spring.jpa.properties.hibernate.format_sql=true

# Logs SQL Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Affiche les valeurs passées dans les requêtes SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE