spring.application.name=davexo-backend

# Server port for execution

server.port=8081

# Connexion à base de données dans conteneur Docker compose
spring.datasource.url=jdbc:postgresql://localhost:5432/davexo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create

#Configuration pour JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Configuration d'emails autorisés
app.allowed-emails=${ALLOWED_EMAILS}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}