spring.application.name=davexo-backend

# Server port for execution

server.port=8081

# Connexion à base de données dans conteneur Docker compose
spring.datasource.url=jdbc:postgresql://localhost:5432/davexo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver PostgreSQL

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate

spring.jpa.hibernate.ddl-auto=create

# Affichage des requêtes SQL dans la console, utile en développement

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true