/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Global administration statistics
 */
export interface AdministrationStatsResponseDto { 
    /**
     * Total number of registered users
     */
    totalUsers: number;
}

