/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request used to create or update a budget
 */
export interface BudgetRequestDto { 
    /**
     * Budget name
     */
    name: string;
    /**
     * Budget amount, strictly greater than 0
     */
    amount: number;
    /**
     * Expense category IDs followed by the budget. An empty list creates a GLOBAL budget; a non-empty list creates a SELECTED_CATEGORIES budget
     */
    followedCategoryIds: Array<number>;
}

