/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Aggregated dashboard data for the authenticated user
 */
export interface BudgetResponseDto { 
    id?: number;
    name?: string;
    amount?: number;
    scope?: BudgetResponseDto.ScopeEnum;
    followedCategoryIds?: Array<number>;
}
export namespace BudgetResponseDto {
    export const ScopeEnum = {
        Global: 'GLOBAL',
        SelectedCategories: 'SELECTED_CATEGORIES'
    } as const;
    export type ScopeEnum = typeof ScopeEnum[keyof typeof ScopeEnum];
}


