/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current month consumption data for a budget
 */
export interface BudgetConsumptionResponseDto { 
    /**
     * Budget identifier
     */
    budgetId?: number;
    /**
     * Configured budget amount
     */
    budgetAmount?: number;
    /**
     * Amount spent during the current month
     */
    spentAmount?: number;
    /**
     * Remaining budget amount. Can be negative when the budget is exceeded
     */
    remainingAmount?: number;
    /**
     * Budget consumption percentage. Can exceed 100 when the budget is exceeded, and can be null if the budget amount is zero
     */
    consumptionPercentage?: number;
}

