/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Budget data
 */
export interface BudgetResponseDto { 
    /**
     * Budget identifier
     */
    id: number;
    /**
     * Budget name
     */
    name: string;
    /**
     * Configured budget amount
     */
    amount: number;
    /**
     * Budget scope
     */
    scope: BudgetResponseDto.ScopeEnum;
    /**
     * Expense category IDs followed by the budget. Empty for a global budget
     */
    followedCategoryIds: Array<number>;
}
export namespace BudgetResponseDto {
    export const ScopeEnum = {
        Global: 'GLOBAL',
        SelectedCategories: 'SELECTED_CATEGORIES'
    } as const;
    export type ScopeEnum = typeof ScopeEnum[keyof typeof ScopeEnum];
}


