/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Standard API error response
 */
export interface CustomErrorResponse { 
    /**
     * HTTP status code
     */
    status: number;
    /**
     * Error type
     */
    error: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Date and time when the error occurred
     */
    timestamp: string;
}

