/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskResponseDto } from './taskResponseDto';
import { BudgetConsumptionResponseDto } from './budgetConsumptionResponseDto';
import { ExpenseResponseDto } from './expenseResponseDto';
import { InventoryItemResponseDto } from './inventoryItemResponseDto';


/**
 * Aggregated dashboard data for the authenticated user
 */
export interface DashboardResponseDto { 
    /**
     * Total amount spent by the user during the current month
     */
    currentMonthExpensesTotal: number;
    /**
     * Total number of tasks currently in TO_DO status
     */
    totalTasksToDo: number;
    /**
     * Total number of inventory items currently included in the shopping list
     */
    totalShoppingItems: number;
    /**
     * Current consumption of the user\'s global budget, or null if no global budget exists
     */
    globalBudgetConsumption: BudgetConsumptionResponseDto | null;
    /**
     * Up to 5 TO_DO tasks ordered by business priority and due date
     */
    tasksToDo: Array<TaskResponseDto>;
    /**
     * Up to 5 shopping list items ordered by shopping priority
     */
    shoppingItems: Array<InventoryItemResponseDto>;
    /**
     * The 10 most recent expenses, ordered by expense date descending
     */
    recentExpenses: Array<ExpenseResponseDto>;
}

