/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Expense statistics breakdown for one category
 */
export interface ExpenseCategoryBreakdownResponseDto { 
    /**
     * Expense category identifier
     */
    categoryId: number;
    /**
     * Expense category name
     */
    categoryName: string;
    /**
     * Total amount spent in the category
     */
    totalAmount: number;
    /**
     * Percentage of total expenses represented by the category
     */
    percentage: number;
}

