/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseCategoryResponseDto { 
    id?: number;
    name?: string;
    budgetId?: number;
    budgetName?: string;
}

