/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Expense category data
 */
export interface ExpenseCategoryResponseDto { 
    /**
     * Expense category identifier
     */
    id: number;
    /**
     * Expense category name
     */
    name: string;
    /**
     * Associated budget identifier, or null if no budget is associated
     */
    budgetId: number | null;
    /**
     * Associated budget name, or null if no budget is associated
     */
    budgetName: string | null;
}

