/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseCategoryBreakdownResponseDto } from './expenseCategoryBreakdownResponseDto';


/**
 * Expense statistics for a requested period
 */
export interface ExpenseStatisticsResponseDto { 
    /**
     * Total amount spent during the requested period
     */
    totalSpent: number;
    /**
     * Expense evolution percentage compared with the previous comparable period, or null when no comparison can be calculated
     */
    evolutionPercentage: number | null;
    /**
     * Historical monthly expense average based on completed months, or null when insufficient history exists
     */
    historicalMonthlyAverage: number | null;
    /**
     * Expense breakdown by category
     */
    categoryBreakdown: Array<ExpenseCategoryBreakdownResponseDto>;
}

