/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseCategoryBreakdownResponseDto } from './expenseCategoryBreakdownResponseDto';


export interface ExpenseStatisticsResponseDto { 
    totalSpent?: number;
    evolutionPercentage?: number;
    historicalMonthlyAverage?: number;
    categoryBreakdown?: Array<ExpenseCategoryBreakdownResponseDto>;
}

