/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Expense data
 */
export interface ExpenseResponseDto { 
    /**
     * Expense identifier
     */
    id: number;
    /**
     * Expense label
     */
    label: string;
    /**
     * Expense amount
     */
    amount: number;
    /**
     * Optional expense note
     */
    note: string | null;
    /**
     * Expense date
     */
    expenseDate: string;
    /**
     * Expense category identifier
     */
    expenseCategoryId: number;
    /**
     * Expense category name
     */
    expenseCategoryName: string;
}

