/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRequestDto { 
    label: string;
    amount: number;
    note?: string;
    expenseDate?: string;
    expenseCategoryId: number;
}

