/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryItemResponseDto { 
    id?: number;
    name?: string;
    type?: InventoryItemResponseDto.TypeEnum;
    status?: InventoryItemResponseDto.StatusEnum;
    note?: string;
    inventoryCategoryId?: number;
    inventoryCategoryName?: string;
}
export namespace InventoryItemResponseDto {
    export const TypeEnum = {
        Consumable: 'CONSUMABLE',
        Durable: 'DURABLE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        InStock: 'IN_STOCK',
        LowStock: 'LOW_STOCK',
        Missing: 'MISSING',
        InService: 'IN_SERVICE',
        OutOfService: 'OUT_OF_SERVICE',
        ToReplace: 'TO_REPLACE',
        NeedMore: 'NEED_MORE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


