/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Inventory item data
 */
export interface InventoryItemResponseDto { 
    /**
     * Inventory item identifier
     */
    id: number;
    /**
     * Inventory item name
     */
    name: string;
    /**
     * Inventory item type
     */
    type: InventoryItemResponseDto.TypeEnum;
    /**
     * Current inventory item status
     */
    status: InventoryItemResponseDto.StatusEnum;
    /**
     * Optional note about the inventory item
     */
    note: string | null;
    /**
     * Inventory category identifier
     */
    inventoryCategoryId: number;
    /**
     * Inventory category name
     */
    inventoryCategoryName: string;
}
export namespace InventoryItemResponseDto {
    export const TypeEnum = {
        Consumable: 'CONSUMABLE',
        Durable: 'DURABLE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        InStock: 'IN_STOCK',
        LowStock: 'LOW_STOCK',
        Missing: 'MISSING',
        InService: 'IN_SERVICE',
        OutOfService: 'OUT_OF_SERVICE',
        ToReplace: 'TO_REPLACE',
        NeedMore: 'NEED_MORE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


