/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Inventory category data
 */
export interface InventoryCategoryResponseDto { 
    /**
     * Inventory category identifier
     */
    id: number;
    /**
     * Inventory category name
     */
    name: string;
}

