/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request used to create or update an inventory item
 */
export interface InventoryItemRequestDto { 
    /**
     * Inventory item name
     */
    name: string;
    /**
     * Inventory item type. CONSUMABLE items and DURABLE items use different allowed statuses
     */
    type: InventoryItemRequestDto.TypeEnum;
    /**
     * Inventory item status. CONSUMABLE statuses: IN_STOCK, LOW_STOCK, MISSING. DURABLE statuses: IN_SERVICE, OUT_OF_SERVICE, TO_REPLACE, NEED_MORE
     */
    status: InventoryItemRequestDto.StatusEnum;
    /**
     * Optional note about the inventory item
     */
    note?: string;
    /**
     * Identifier of the inventory category associated with the item
     */
    inventoryCategoryId: number;
}
export namespace InventoryItemRequestDto {
    export const TypeEnum = {
        Consumable: 'CONSUMABLE',
        Durable: 'DURABLE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        InStock: 'IN_STOCK',
        LowStock: 'LOW_STOCK',
        Missing: 'MISSING',
        InService: 'IN_SERVICE',
        OutOfService: 'OUT_OF_SERVICE',
        ToReplace: 'TO_REPLACE',
        NeedMore: 'NEED_MORE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


