/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Authentication result returned after a successful login
 */
export interface LoginResponseDto { 
    /**
     * JWT access token
     */
    token: string;
    /**
     * Authenticated user identifier
     */
    userId: number;
    /**
     * Authenticated user\'s pseudo
     */
    pseudo: string;
    /**
     * Authenticated user\'s email
     */
    email: string;
    /**
     * Authenticated user\'s role
     */
    role: LoginResponseDto.RoleEnum;
}
export namespace LoginResponseDto {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


