/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponseDto { 
    token?: string;
    userId?: number;
    pseudo?: string;
    email?: string;
    role?: LoginResponseDto.RoleEnum;
}
export namespace LoginResponseDto {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


