/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Effective period used to calculate statistics
 */
export interface PeriodResponseDto { 
    /**
     * Statistics period type
     */
    periodType?: PeriodResponseDto.PeriodTypeEnum;
    /**
     * First date included in the statistics period
     */
    startDate?: string;
    /**
     * Last date included in the statistics period
     */
    endDate?: string;
}
export namespace PeriodResponseDto {
    export const PeriodTypeEnum = {
        Day: 'DAY',
        Week: 'WEEK',
        Month: 'MONTH',
        Year: 'YEAR'
    } as const;
    export type PeriodTypeEnum = typeof PeriodTypeEnum[keyof typeof PeriodTypeEnum];
}


