/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemResponseDto } from './inventoryItemResponseDto';


/**
 * Shopping list grouped by business priority
 */
export interface ShoppingListResponseDto { 
    /**
     * High priority items: MISSING and TO_REPLACE
     */
    highPriorityItems?: Array<InventoryItemResponseDto>;
    /**
     * Medium priority items: LOW_STOCK and NEED_MORE
     */
    mediumPriorityItems?: Array<InventoryItemResponseDto>;
    /**
     * Low priority items: OUT_OF_SERVICE
     */
    lowPriorityItems?: Array<InventoryItemResponseDto>;
    /**
     * Total number of items included in the shopping list
     */
    totalItems?: number;
}

