/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodResponseDto } from './periodResponseDto';
import { TaskStatisticsResponseDto } from './taskStatisticsResponseDto';
import { ExpenseStatisticsResponseDto } from './expenseStatisticsResponseDto';


/**
 * Aggregated expense and task statistics for a requested period
 */
export interface StatisticsResponseDto { 
    /**
     * Effective statistics period
     */
    period: PeriodResponseDto;
    /**
     * Expense statistics calculated for the period
     */
    expenses: ExpenseStatisticsResponseDto;
    /**
     * Task statistics calculated for the period
     */
    tasks: TaskStatisticsResponseDto;
}

