/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Task data
 */
export interface TaskResponseDto { 
    /**
     * Task identifier
     */
    id: number;
    /**
     * Task title
     */
    title: string;
    /**
     * Task priority
     */
    priority: TaskResponseDto.PriorityEnum;
    /**
     * Current task status
     */
    status: TaskResponseDto.StatusEnum;
    /**
     * Task creation date
     */
    createdAt: string;
    /**
     * Optional task due date
     */
    dueDate: string | null;
    /**
     * Completion date, or null when the task is not completed
     */
    completedAt: string | null;
    /**
     * Optional task note
     */
    note: string | null;
}
export namespace TaskResponseDto {
    export const PriorityEnum = {
        Urgent: 'URGENT',
        Important: 'IMPORTANT',
        NonCritical: 'NON_CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
    export const StatusEnum = {
        ToDo: 'TO_DO',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


