/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskCreateRequestDto { 
    title: string;
    priority: TaskCreateRequestDto.PriorityEnum;
    dueDate?: string | null;
    note?: string | null;
}
export namespace TaskCreateRequestDto {
    export const PriorityEnum = {
        Urgent: 'URGENT',
        Important: 'IMPORTANT',
        NonCritical: 'NON_CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


