/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPriorityBreakdownResponseDto } from './taskPriorityBreakdownResponseDto';


export interface TaskStatisticsResponseDto { 
    completionRate?: number;
    deadlineRespectRate?: number;
    averageCompletionTimeDays?: number;
    priorityBreakdown?: Array<TaskPriorityBreakdownResponseDto>;
}

