/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskUpdateRequestDto { 
    title: string;
    priority: TaskUpdateRequestDto.PriorityEnum;
    status: TaskUpdateRequestDto.StatusEnum;
    dueDate?: string;
    completedAt?: string;
    note?: string;
}
export namespace TaskUpdateRequestDto {
    export const PriorityEnum = {
        Urgent: 'URGENT',
        Important: 'IMPORTANT',
        NonCritical: 'NON_CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
    export const StatusEnum = {
        ToDo: 'TO_DO',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


