/**
 * Davexo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Completed task statistics for one priority
 */
export interface TaskPriorityBreakdownResponseDto { 
    /**
     * Task priority
     */
    priority: TaskPriorityBreakdownResponseDto.PriorityEnum;
    /**
     * Number of completed tasks with this priority
     */
    count: number;
    /**
     * Percentage of completed tasks represented by this priority
     */
    percentage: number;
}
export namespace TaskPriorityBreakdownResponseDto {
    export const PriorityEnum = {
        Urgent: 'URGENT',
        Important: 'IMPORTANT',
        NonCritical: 'NON_CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


