export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './budgets.service';
import { BudgetsService } from './budgets.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './expenseCategories.service';
import { ExpenseCategoriesService } from './expenseCategories.service';
export * from './expenses.service';
import { ExpensesService } from './expenses.service';
export * from './inventoryCategories.service';
import { InventoryCategoriesService } from './inventoryCategories.service';
export * from './inventoryItems.service';
import { InventoryItemsService } from './inventoryItems.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export const APIS = [AdministrationService, AuthenticationService, BudgetsService, DashboardService, ExpenseCategoriesService, ExpensesService, InventoryCategoriesService, InventoryItemsService, StatisticsService, TasksService];
